FROM python:3.10.2-slim-buster

COPY requirements.txt ./

COPY . .

RUN pip install --upgrade pip

RUN pip install scrapy

RUN pip install requests

RUN pip install mysql-connector-python


ENTRYPOINT [ "/bin/sh","startcrawl.sh" ]